// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	EventType string                `json:"event_type"`
	UserID    uuid.NullUUID         `json:"user_id"`
	ClientID  uuid.NullUUID         `json:"client_id"`
	Result    string                `json:"result"`
	IpAddress sql.NullString        `json:"ip_address"`
	UserAgent sql.NullString        `json:"user_agent"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
}

type AuthorizationCode struct {
	ID                  uuid.UUID    `json:"id"`
	CodeHash            string       `json:"code_hash"`
	ClientID            uuid.UUID    `json:"client_id"`
	UserID              uuid.UUID    `json:"user_id"`
	RedirectUri         string       `json:"redirect_uri"`
	Scope               string       `json:"scope"`
	Nonce               string       `json:"nonce"`
	CodeChallenge       string       `json:"code_challenge"`
	CodeChallengeMethod string       `json:"code_challenge_method"`
	AuthTime            time.Time    `json:"auth_time"`
	ExpiresAt           time.Time    `json:"expires_at"`
	UsedAt              sql.NullTime `json:"used_at"`
	CreatedAt           time.Time    `json:"created_at"`
}

type AuthorizationRequest struct {
	ID                  uuid.UUID     `json:"id"`
	RequestIDHash       string        `json:"request_id_hash"`
	ClientID            uuid.UUID     `json:"client_id"`
	RedirectUri         string        `json:"redirect_uri"`
	Scope               string        `json:"scope"`
	State               string        `json:"state"`
	Nonce               string        `json:"nonce"`
	CodeChallenge       string        `json:"code_challenge"`
	CodeChallengeMethod string        `json:"code_challenge_method"`
	RequestedAt         time.Time     `json:"requested_at"`
	ExpiresAt           time.Time     `json:"expires_at"`
	UserID              uuid.NullUUID `json:"user_id"`
	CompletedAt         sql.NullTime  `json:"completed_at"`
}

type Client struct {
	ID                      uuid.UUID      `json:"id"`
	ClientID                string         `json:"client_id"`
	ClientName              string         `json:"client_name"`
	ClientType              string         `json:"client_type"`
	ClientSecretHash        sql.NullString `json:"client_secret_hash"`
	TokenEndpointAuthMethod string         `json:"token_endpoint_auth_method"`
	RequirePkce             bool           `json:"require_pkce"`
	Status                  string         `json:"status"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

type ClientAllowedScope struct {
	ClientID uuid.UUID `json:"client_id"`
	Scope    string    `json:"scope"`
}

type ClientRedirectUri struct {
	ID          uuid.UUID `json:"id"`
	ClientID    uuid.UUID `json:"client_id"`
	RedirectUri string    `json:"redirect_uri"`
	CreatedAt   time.Time `json:"created_at"`
}

type EmailOtpChallenge struct {
	ID              uuid.UUID    `json:"id"`
	ChallengeIDHash string       `json:"challenge_id_hash"`
	UserID          uuid.UUID    `json:"user_id"`
	OtpHash         string       `json:"otp_hash"`
	Attempts        int32        `json:"attempts"`
	MaxAttempts     int32        `json:"max_attempts"`
	ExpiresAt       time.Time    `json:"expires_at"`
	UsedAt          sql.NullTime `json:"used_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

type LoginSession struct {
	ID          uuid.UUID      `json:"id"`
	SessionHash string         `json:"session_hash"`
	UserID      uuid.UUID      `json:"user_id"`
	AuthTime    time.Time      `json:"auth_time"`
	Amr         string         `json:"amr"`
	IpAddress   sql.NullString `json:"ip_address"`
	UserAgent   sql.NullString `json:"user_agent"`
	ExpiresAt   time.Time      `json:"expires_at"`
	RevokedAt   sql.NullTime   `json:"revoked_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type PendingUserRegistration struct {
	ID                    uuid.UUID    `json:"id"`
	Email                 string       `json:"email"`
	PasswordHash          string       `json:"password_hash"`
	FamilyName            string       `json:"family_name"`
	GivenName             string       `json:"given_name"`
	FamilyNameKana        string       `json:"family_name_kana"`
	GivenNameKana         string       `json:"given_name_kana"`
	Gender                string       `json:"gender"`
	Birthdate             time.Time    `json:"birthdate"`
	CountryCode           string       `json:"country_code"`
	VerificationTokenHash string       `json:"verification_token_hash"`
	ExpiresAt             time.Time    `json:"expires_at"`
	UsedAt                sql.NullTime `json:"used_at"`
	CreatedAt             time.Time    `json:"created_at"`
}

type RefreshToken struct {
	ID              uuid.UUID     `json:"id"`
	TokenHash       string        `json:"token_hash"`
	TokenFamilyID   uuid.UUID     `json:"token_family_id"`
	ClientID        uuid.UUID     `json:"client_id"`
	UserID          uuid.UUID     `json:"user_id"`
	Scope           string        `json:"scope"`
	ParentID        uuid.NullUUID `json:"parent_id"`
	RotatedToID     uuid.NullUUID `json:"rotated_to_id"`
	IssuedAt        time.Time     `json:"issued_at"`
	LastUsedAt      sql.NullTime  `json:"last_used_at"`
	ExpiresAt       time.Time     `json:"expires_at"`
	RevokedAt       sql.NullTime  `json:"revoked_at"`
	ReuseDetectedAt sql.NullTime  `json:"reuse_detected_at"`
}

type SigningKey struct {
	ID                      uuid.UUID       `json:"id"`
	Kid                     string          `json:"kid"`
	Alg                     string          `json:"alg"`
	PublicJwk               json.RawMessage `json:"public_jwk"`
	PrivateKeyParameterName string          `json:"private_key_parameter_name"`
	Status                  string          `json:"status"`
	NotBefore               time.Time       `json:"not_before"`
	NotAfter                sql.NullTime    `json:"not_after"`
	CreatedAt               time.Time       `json:"created_at"`
}

type User struct {
	ID              uuid.UUID `json:"id"`
	Sub             string    `json:"sub"`
	Email           string    `json:"email"`
	EmailVerifiedAt time.Time `json:"email_verified_at"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type UserPasswordCredential struct {
	UserID            uuid.UUID `json:"user_id"`
	PasswordHash      string    `json:"password_hash"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UserProfile struct {
	UserID         uuid.UUID      `json:"user_id"`
	FamilyName     sql.NullString `json:"family_name"`
	GivenName      sql.NullString `json:"given_name"`
	FamilyNameKana sql.NullString `json:"family_name_kana"`
	GivenNameKana  sql.NullString `json:"given_name_kana"`
	Gender         sql.NullString `json:"gender"`
	Birthdate      sql.NullTime   `json:"birthdate"`
	CountryCode    sql.NullString `json:"country_code"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type UserWithdrawal struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Reason      sql.NullString `json:"reason"`
	IpAddress   sql.NullString `json:"ip_address"`
	UserAgent   sql.NullString `json:"user_agent"`
	WithdrawnAt time.Time      `json:"withdrawn_at"`
}
