// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteAuthorizationRequest(ctx context.Context, arg CompleteAuthorizationRequestParams) (AuthorizationRequest, error)
	// Audit Logs
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (AuthorizationCode, error)
	CreateAuthorizationRequest(ctx context.Context, arg CreateAuthorizationRequestParams) (AuthorizationRequest, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateClientAllowedScope(ctx context.Context, arg CreateClientAllowedScopeParams) error
	CreateClientRedirectURI(ctx context.Context, arg CreateClientRedirectURIParams) (ClientRedirectUri, error)
	CreateEmailOTPChallenge(ctx context.Context, arg CreateEmailOTPChallengeParams) (EmailOtpChallenge, error)
	CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) (LoginSession, error)
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (UserPasswordCredential, error)
	CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) (PendingUserRegistration, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) (SigningKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	// User Withdrawals
	CreateUserWithdrawal(ctx context.Context, arg CreateUserWithdrawalParams) (UserWithdrawal, error)
	GetActiveSigningKeys(ctx context.Context) ([]SigningKey, error)
	// Authorization Codes
	GetAuthorizationCode(ctx context.Context, codeHash string) (AuthorizationCode, error)
	// Authorization Requests
	GetAuthorizationRequest(ctx context.Context, requestIDHash string) (AuthorizationRequest, error)
	// Client Allowed Scopes
	GetClientAllowedScopes(ctx context.Context, clientID uuid.UUID) ([]string, error)
	GetClientByClientID(ctx context.Context, clientID string) (Client, error)
	// Clients
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	// Client Redirect URIs
	GetClientRedirectURIs(ctx context.Context, clientID uuid.UUID) ([]ClientRedirectUri, error)
	// Email OTP Challenges
	GetEmailOTPChallenge(ctx context.Context, challengeIDHash string) (EmailOtpChallenge, error)
	// Login Sessions
	GetLoginSession(ctx context.Context, sessionHash string) (LoginSession, error)
	// User Password Credentials
	GetPasswordCredential(ctx context.Context, userID uuid.UUID) (UserPasswordCredential, error)
	// Pending User Registrations
	GetPendingRegistrationByToken(ctx context.Context, verificationTokenHash string) (PendingUserRegistration, error)
	// Refresh Tokens
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	// Signing Keys
	GetSigningKey(ctx context.Context, kid string) (SigningKey, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// queries.sql
	// Users
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserBySub(ctx context.Context, sub string) (User, error)
	// User Profiles
	GetUserProfile(ctx context.Context, userID uuid.UUID) (UserProfile, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (EmailOtpChallenge, error)
	MarkOTPUsed(ctx context.Context, id uuid.UUID) error
	MarkPendingRegistrationUsed(ctx context.Context, id uuid.UUID) error
	MarkRefreshTokenReuse(ctx context.Context, id uuid.UUID) error
	RevokeLoginSession(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, tokenFamilyID uuid.UUID) error
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error
	UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) (UserPasswordCredential, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UseAuthorizationCode(ctx context.Context, codeHash string) (AuthorizationCode, error)
	WithdrawUser(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
