// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const completeAuthorizationRequest = `-- name: CompleteAuthorizationRequest :one
UPDATE authorization_requests
SET user_id = $2, completed_at = now()
WHERE id = $1
RETURNING id, request_id_hash, client_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, requested_at, expires_at, user_id, completed_at
`

type CompleteAuthorizationRequestParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"user_id"`
}

func (q *Queries) CompleteAuthorizationRequest(ctx context.Context, arg CompleteAuthorizationRequestParams) (AuthorizationRequest, error) {
	row := q.db.QueryRowContext(ctx, completeAuthorizationRequest, arg.ID, arg.UserID)
	var i AuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.RequestIDHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.CompletedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (id, event_type, user_id, client_id, result, ip_address, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, event_type, user_id, client_id, result, ip_address, user_agent, metadata, created_at
`

type CreateAuditLogParams struct {
	ID        uuid.UUID             `json:"id"`
	EventType string                `json:"event_type"`
	UserID    uuid.NullUUID         `json:"user_id"`
	ClientID  uuid.NullUUID         `json:"client_id"`
	Result    string                `json:"result"`
	IpAddress sql.NullString        `json:"ip_address"`
	UserAgent sql.NullString        `json:"user_agent"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

// Audit Logs
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.ID,
		arg.EventType,
		arg.UserID,
		arg.ClientID,
		arg.Result,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.UserID,
		&i.ClientID,
		&i.Result,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO authorization_codes (id, code_hash, client_id, user_id, redirect_uri, scope, nonce, code_challenge, code_challenge_method, auth_time, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, code_hash, client_id, user_id, redirect_uri, scope, nonce, code_challenge, code_challenge_method, auth_time, expires_at, used_at, created_at
`

type CreateAuthorizationCodeParams struct {
	ID                  uuid.UUID `json:"id"`
	CodeHash            string    `json:"code_hash"`
	ClientID            uuid.UUID `json:"client_id"`
	UserID              uuid.UUID `json:"user_id"`
	RedirectUri         string    `json:"redirect_uri"`
	Scope               string    `json:"scope"`
	Nonce               string    `json:"nonce"`
	CodeChallenge       string    `json:"code_challenge"`
	CodeChallengeMethod string    `json:"code_challenge_method"`
	AuthTime            time.Time `json:"auth_time"`
	ExpiresAt           time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (AuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, createAuthorizationCode,
		arg.ID,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.Scope,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.AuthTime,
		arg.ExpiresAt,
	)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthTime,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthorizationRequest = `-- name: CreateAuthorizationRequest :one
INSERT INTO authorization_requests (id, request_id_hash, client_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, request_id_hash, client_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, requested_at, expires_at, user_id, completed_at
`

type CreateAuthorizationRequestParams struct {
	ID                  uuid.UUID `json:"id"`
	RequestIDHash       string    `json:"request_id_hash"`
	ClientID            uuid.UUID `json:"client_id"`
	RedirectUri         string    `json:"redirect_uri"`
	Scope               string    `json:"scope"`
	State               string    `json:"state"`
	Nonce               string    `json:"nonce"`
	CodeChallenge       string    `json:"code_challenge"`
	CodeChallengeMethod string    `json:"code_challenge_method"`
	ExpiresAt           time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthorizationRequest(ctx context.Context, arg CreateAuthorizationRequestParams) (AuthorizationRequest, error) {
	row := q.db.QueryRowContext(ctx, createAuthorizationRequest,
		arg.ID,
		arg.RequestIDHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scope,
		arg.State,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i AuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.RequestIDHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.CompletedAt,
	)
	return i, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, client_id, client_name, client_type, client_secret_hash, token_endpoint_auth_method, require_pkce, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, client_name, client_type, client_secret_hash, token_endpoint_auth_method, require_pkce, status, created_at, updated_at
`

type CreateClientParams struct {
	ID                      uuid.UUID      `json:"id"`
	ClientID                string         `json:"client_id"`
	ClientName              string         `json:"client_name"`
	ClientType              string         `json:"client_type"`
	ClientSecretHash        sql.NullString `json:"client_secret_hash"`
	TokenEndpointAuthMethod string         `json:"token_endpoint_auth_method"`
	RequirePkce             bool           `json:"require_pkce"`
	Status                  string         `json:"status"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.ClientID,
		arg.ClientName,
		arg.ClientType,
		arg.ClientSecretHash,
		arg.TokenEndpointAuthMethod,
		arg.RequirePkce,
		arg.Status,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientType,
		&i.ClientSecretHash,
		&i.TokenEndpointAuthMethod,
		&i.RequirePkce,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClientAllowedScope = `-- name: CreateClientAllowedScope :exec
INSERT INTO client_allowed_scopes (client_id, scope)
VALUES ($1, $2)
`

type CreateClientAllowedScopeParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Scope    string    `json:"scope"`
}

func (q *Queries) CreateClientAllowedScope(ctx context.Context, arg CreateClientAllowedScopeParams) error {
	_, err := q.db.ExecContext(ctx, createClientAllowedScope, arg.ClientID, arg.Scope)
	return err
}

const createClientRedirectURI = `-- name: CreateClientRedirectURI :one
INSERT INTO client_redirect_uris (id, client_id, redirect_uri)
VALUES ($1, $2, $3)
RETURNING id, client_id, redirect_uri, created_at
`

type CreateClientRedirectURIParams struct {
	ID          uuid.UUID `json:"id"`
	ClientID    uuid.UUID `json:"client_id"`
	RedirectUri string    `json:"redirect_uri"`
}

func (q *Queries) CreateClientRedirectURI(ctx context.Context, arg CreateClientRedirectURIParams) (ClientRedirectUri, error) {
	row := q.db.QueryRowContext(ctx, createClientRedirectURI, arg.ID, arg.ClientID, arg.RedirectUri)
	var i ClientRedirectUri
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailOTPChallenge = `-- name: CreateEmailOTPChallenge :one
INSERT INTO email_otp_challenges (id, challenge_id_hash, user_id, otp_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, challenge_id_hash, user_id, otp_hash, attempts, max_attempts, expires_at, used_at, created_at
`

type CreateEmailOTPChallengeParams struct {
	ID              uuid.UUID `json:"id"`
	ChallengeIDHash string    `json:"challenge_id_hash"`
	UserID          uuid.UUID `json:"user_id"`
	OtpHash         string    `json:"otp_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailOTPChallenge(ctx context.Context, arg CreateEmailOTPChallengeParams) (EmailOtpChallenge, error) {
	row := q.db.QueryRowContext(ctx, createEmailOTPChallenge,
		arg.ID,
		arg.ChallengeIDHash,
		arg.UserID,
		arg.OtpHash,
		arg.ExpiresAt,
	)
	var i EmailOtpChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeIDHash,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLoginSession = `-- name: CreateLoginSession :one
INSERT INTO login_sessions (id, session_hash, user_id, auth_time, amr, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, session_hash, user_id, auth_time, amr, ip_address, user_agent, expires_at, revoked_at, created_at
`

type CreateLoginSessionParams struct {
	ID          uuid.UUID      `json:"id"`
	SessionHash string         `json:"session_hash"`
	UserID      uuid.UUID      `json:"user_id"`
	AuthTime    time.Time      `json:"auth_time"`
	Amr         string         `json:"amr"`
	IpAddress   sql.NullString `json:"ip_address"`
	UserAgent   sql.NullString `json:"user_agent"`
	ExpiresAt   time.Time      `json:"expires_at"`
}

func (q *Queries) CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) (LoginSession, error) {
	row := q.db.QueryRowContext(ctx, createLoginSession,
		arg.ID,
		arg.SessionHash,
		arg.UserID,
		arg.AuthTime,
		arg.Amr,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.SessionHash,
		&i.UserID,
		&i.AuthTime,
		&i.Amr,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :one
INSERT INTO user_password_credentials (user_id, password_hash)
VALUES ($1, $2)
RETURNING user_id, password_hash, password_changed_at, created_at
`

type CreatePasswordCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (UserPasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, createPasswordCredential, arg.UserID, arg.PasswordHash)
	var i UserPasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :one
INSERT INTO pending_user_registrations (id, email, password_hash, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code, verification_token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, email, password_hash, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code, verification_token_hash, expires_at, used_at, created_at
`

type CreatePendingRegistrationParams struct {
	ID                    uuid.UUID `json:"id"`
	Email                 string    `json:"email"`
	PasswordHash          string    `json:"password_hash"`
	FamilyName            string    `json:"family_name"`
	GivenName             string    `json:"given_name"`
	FamilyNameKana        string    `json:"family_name_kana"`
	GivenNameKana         string    `json:"given_name_kana"`
	Gender                string    `json:"gender"`
	Birthdate             time.Time `json:"birthdate"`
	CountryCode           string    `json:"country_code"`
	VerificationTokenHash string    `json:"verification_token_hash"`
	ExpiresAt             time.Time `json:"expires_at"`
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) (PendingUserRegistration, error) {
	row := q.db.QueryRowContext(ctx, createPendingRegistration,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FamilyName,
		arg.GivenName,
		arg.FamilyNameKana,
		arg.GivenNameKana,
		arg.Gender,
		arg.Birthdate,
		arg.CountryCode,
		arg.VerificationTokenHash,
		arg.ExpiresAt,
	)
	var i PendingUserRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FamilyName,
		&i.GivenName,
		&i.FamilyNameKana,
		&i.GivenNameKana,
		&i.Gender,
		&i.Birthdate,
		&i.CountryCode,
		&i.VerificationTokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, token_hash, token_family_id, client_id, user_id, scope, parent_id, rotated_to_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, token_hash, token_family_id, client_id, user_id, scope, parent_id, rotated_to_id, issued_at, last_used_at, expires_at, revoked_at, reuse_detected_at
`

type CreateRefreshTokenParams struct {
	ID            uuid.UUID     `json:"id"`
	TokenHash     string        `json:"token_hash"`
	TokenFamilyID uuid.UUID     `json:"token_family_id"`
	ClientID      uuid.UUID     `json:"client_id"`
	UserID        uuid.UUID     `json:"user_id"`
	Scope         string        `json:"scope"`
	ParentID      uuid.NullUUID `json:"parent_id"`
	RotatedToID   uuid.NullUUID `json:"rotated_to_id"`
	ExpiresAt     time.Time     `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.TokenFamilyID,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.ParentID,
		arg.RotatedToID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenFamilyID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ParentID,
		&i.RotatedToID,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
	)
	return i, err
}

const createSigningKey = `-- name: CreateSigningKey :one
INSERT INTO signing_keys (id, kid, alg, public_jwk, private_key_parameter_name, status, not_before, not_after)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, kid, alg, public_jwk, private_key_parameter_name, status, not_before, not_after, created_at
`

type CreateSigningKeyParams struct {
	ID                      uuid.UUID       `json:"id"`
	Kid                     string          `json:"kid"`
	Alg                     string          `json:"alg"`
	PublicJwk               json.RawMessage `json:"public_jwk"`
	PrivateKeyParameterName string          `json:"private_key_parameter_name"`
	Status                  string          `json:"status"`
	NotBefore               time.Time       `json:"not_before"`
	NotAfter                sql.NullTime    `json:"not_after"`
}

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRowContext(ctx, createSigningKey,
		arg.ID,
		arg.Kid,
		arg.Alg,
		arg.PublicJwk,
		arg.PrivateKeyParameterName,
		arg.Status,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Alg,
		&i.PublicJwk,
		&i.PrivateKeyParameterName,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, sub, email, email_verified_at, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sub, email, email_verified_at, status, created_at, updated_at
`

type CreateUserParams struct {
	ID              uuid.UUID `json:"id"`
	Sub             string    `json:"sub"`
	Email           string    `json:"email"`
	EmailVerifiedAt time.Time `json:"email_verified_at"`
	Status          string    `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Sub,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (user_id, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING user_id, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code, updated_at
`

type CreateUserProfileParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	FamilyName     sql.NullString `json:"family_name"`
	GivenName      sql.NullString `json:"given_name"`
	FamilyNameKana sql.NullString `json:"family_name_kana"`
	GivenNameKana  sql.NullString `json:"given_name_kana"`
	Gender         sql.NullString `json:"gender"`
	Birthdate      sql.NullTime   `json:"birthdate"`
	CountryCode    sql.NullString `json:"country_code"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, createUserProfile,
		arg.UserID,
		arg.FamilyName,
		arg.GivenName,
		arg.FamilyNameKana,
		arg.GivenNameKana,
		arg.Gender,
		arg.Birthdate,
		arg.CountryCode,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FamilyName,
		&i.GivenName,
		&i.FamilyNameKana,
		&i.GivenNameKana,
		&i.Gender,
		&i.Birthdate,
		&i.CountryCode,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithdrawal = `-- name: CreateUserWithdrawal :one
INSERT INTO user_withdrawals (id, user_id, reason, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, reason, ip_address, user_agent, withdrawn_at
`

type CreateUserWithdrawalParams struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Reason    sql.NullString `json:"reason"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

// User Withdrawals
func (q *Queries) CreateUserWithdrawal(ctx context.Context, arg CreateUserWithdrawalParams) (UserWithdrawal, error) {
	row := q.db.QueryRowContext(ctx, createUserWithdrawal,
		arg.ID,
		arg.UserID,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UserWithdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.WithdrawnAt,
	)
	return i, err
}

const getActiveSigningKeys = `-- name: GetActiveSigningKeys :many
SELECT id, kid, alg, public_jwk, private_key_parameter_name, status, not_before, not_after, created_at FROM signing_keys WHERE status = 'active' OR status = 'standby' ORDER BY created_at DESC
`

func (q *Queries) GetActiveSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.Alg,
			&i.PublicJwk,
			&i.PrivateKeyParameterName,
			&i.Status,
			&i.NotBefore,
			&i.NotAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT id, code_hash, client_id, user_id, redirect_uri, scope, nonce, code_challenge, code_challenge_method, auth_time, expires_at, used_at, created_at FROM authorization_codes WHERE code_hash = $1
`

// Authorization Codes
func (q *Queries) GetAuthorizationCode(ctx context.Context, codeHash string) (AuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationCode, codeHash)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthTime,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorizationRequest = `-- name: GetAuthorizationRequest :one
SELECT id, request_id_hash, client_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, requested_at, expires_at, user_id, completed_at FROM authorization_requests WHERE request_id_hash = $1
`

// Authorization Requests
func (q *Queries) GetAuthorizationRequest(ctx context.Context, requestIDHash string) (AuthorizationRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationRequest, requestIDHash)
	var i AuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.RequestIDHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.CompletedAt,
	)
	return i, err
}

const getClientAllowedScopes = `-- name: GetClientAllowedScopes :many
SELECT scope FROM client_allowed_scopes WHERE client_id = $1
`

// Client Allowed Scopes
func (q *Queries) GetClientAllowedScopes(ctx context.Context, clientID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getClientAllowedScopes, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, client_id, client_name, client_type, client_secret_hash, token_endpoint_auth_method, require_pkce, status, created_at, updated_at FROM clients WHERE client_id = $1
`

func (q *Queries) GetClientByClientID(ctx context.Context, clientID string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByClientID, clientID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientType,
		&i.ClientSecretHash,
		&i.TokenEndpointAuthMethod,
		&i.RequirePkce,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_id, client_name, client_type, client_secret_hash, token_endpoint_auth_method, require_pkce, status, created_at, updated_at FROM clients WHERE id = $1
`

// Clients
func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientType,
		&i.ClientSecretHash,
		&i.TokenEndpointAuthMethod,
		&i.RequirePkce,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientRedirectURIs = `-- name: GetClientRedirectURIs :many
SELECT id, client_id, redirect_uri, created_at FROM client_redirect_uris WHERE client_id = $1
`

// Client Redirect URIs
func (q *Queries) GetClientRedirectURIs(ctx context.Context, clientID uuid.UUID) ([]ClientRedirectUri, error) {
	rows, err := q.db.QueryContext(ctx, getClientRedirectURIs, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientRedirectUri
	for rows.Next() {
		var i ClientRedirectUri
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.RedirectUri,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailOTPChallenge = `-- name: GetEmailOTPChallenge :one
SELECT id, challenge_id_hash, user_id, otp_hash, attempts, max_attempts, expires_at, used_at, created_at FROM email_otp_challenges WHERE challenge_id_hash = $1
`

// Email OTP Challenges
func (q *Queries) GetEmailOTPChallenge(ctx context.Context, challengeIDHash string) (EmailOtpChallenge, error) {
	row := q.db.QueryRowContext(ctx, getEmailOTPChallenge, challengeIDHash)
	var i EmailOtpChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeIDHash,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLoginSession = `-- name: GetLoginSession :one
SELECT id, session_hash, user_id, auth_time, amr, ip_address, user_agent, expires_at, revoked_at, created_at FROM login_sessions WHERE session_hash = $1
`

// Login Sessions
func (q *Queries) GetLoginSession(ctx context.Context, sessionHash string) (LoginSession, error) {
	row := q.db.QueryRowContext(ctx, getLoginSession, sessionHash)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.SessionHash,
		&i.UserID,
		&i.AuthTime,
		&i.Amr,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT user_id, password_hash, password_changed_at, created_at FROM user_password_credentials WHERE user_id = $1
`

// User Password Credentials
func (q *Queries) GetPasswordCredential(ctx context.Context, userID uuid.UUID) (UserPasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredential, userID)
	var i UserPasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRegistrationByToken = `-- name: GetPendingRegistrationByToken :one
SELECT id, email, password_hash, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code, verification_token_hash, expires_at, used_at, created_at FROM pending_user_registrations WHERE verification_token_hash = $1
`

// Pending User Registrations
func (q *Queries) GetPendingRegistrationByToken(ctx context.Context, verificationTokenHash string) (PendingUserRegistration, error) {
	row := q.db.QueryRowContext(ctx, getPendingRegistrationByToken, verificationTokenHash)
	var i PendingUserRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FamilyName,
		&i.GivenName,
		&i.FamilyNameKana,
		&i.GivenNameKana,
		&i.Gender,
		&i.Birthdate,
		&i.CountryCode,
		&i.VerificationTokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token_hash, token_family_id, client_id, user_id, scope, parent_id, rotated_to_id, issued_at, last_used_at, expires_at, revoked_at, reuse_detected_at FROM refresh_tokens WHERE token_hash = $1
`

// Refresh Tokens
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenFamilyID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ParentID,
		&i.RotatedToID,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
	)
	return i, err
}

const getSigningKey = `-- name: GetSigningKey :one
SELECT id, kid, alg, public_jwk, private_key_parameter_name, status, not_before, not_after, created_at FROM signing_keys WHERE kid = $1
`

// Signing Keys
func (q *Queries) GetSigningKey(ctx context.Context, kid string) (SigningKey, error) {
	row := q.db.QueryRowContext(ctx, getSigningKey, kid)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Alg,
		&i.PublicJwk,
		&i.PrivateKeyParameterName,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, sub, email, email_verified_at, status, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, sub, email, email_verified_at, status, created_at, updated_at FROM users WHERE id = $1
`

// queries.sql
// Users
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, sub, email, email_verified_at, status, created_at, updated_at FROM users WHERE sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, sub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code, updated_at FROM user_profiles WHERE user_id = $1
`

// User Profiles
func (q *Queries) GetUserProfile(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FamilyName,
		&i.GivenName,
		&i.FamilyNameKana,
		&i.GivenNameKana,
		&i.Gender,
		&i.Birthdate,
		&i.CountryCode,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE email_otp_challenges
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, challenge_id_hash, user_id, otp_hash, attempts, max_attempts, expires_at, used_at, created_at
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (EmailOtpChallenge, error) {
	row := q.db.QueryRowContext(ctx, incrementOTPAttempts, id)
	var i EmailOtpChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeIDHash,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE email_otp_challenges
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOTPUsed, id)
	return err
}

const markPendingRegistrationUsed = `-- name: MarkPendingRegistrationUsed :exec
UPDATE pending_user_registrations
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkPendingRegistrationUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPendingRegistrationUsed, id)
	return err
}

const markRefreshTokenReuse = `-- name: MarkRefreshTokenReuse :exec
UPDATE refresh_tokens
SET reuse_detected_at = now()
WHERE id = $1
`

func (q *Queries) MarkRefreshTokenReuse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markRefreshTokenReuse, id)
	return err
}

const revokeLoginSession = `-- name: RevokeLoginSession :exec
UPDATE login_sessions
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeLoginSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeLoginSession, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_family_id = $1
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, tokenFamilyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenFamily, tokenFamilyID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now(), rotated_to_id = $2
WHERE id = $1
`

type RotateRefreshTokenParams struct {
	ID          uuid.UUID     `json:"id"`
	RotatedToID uuid.NullUUID `json:"rotated_to_id"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, rotateRefreshToken, arg.ID, arg.RotatedToID)
	return err
}

const updatePasswordCredential = `-- name: UpdatePasswordCredential :one
UPDATE user_password_credentials
SET password_hash = $2, password_changed_at = now()
WHERE user_id = $1
RETURNING user_id, password_hash, password_changed_at, created_at
`

type UpdatePasswordCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) (UserPasswordCredential, error) {
	row := q.db.QueryRowContext(ctx, updatePasswordCredential, arg.UserID, arg.PasswordHash)
	var i UserPasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET family_name = $2, given_name = $3, family_name_kana = $4, given_name_kana = $5, gender = $6, birthdate = $7, country_code = $8, updated_at = now()
WHERE user_id = $1
RETURNING user_id, family_name, given_name, family_name_kana, given_name_kana, gender, birthdate, country_code, updated_at
`

type UpdateUserProfileParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	FamilyName     sql.NullString `json:"family_name"`
	GivenName      sql.NullString `json:"given_name"`
	FamilyNameKana sql.NullString `json:"family_name_kana"`
	GivenNameKana  sql.NullString `json:"given_name_kana"`
	Gender         sql.NullString `json:"gender"`
	Birthdate      sql.NullTime   `json:"birthdate"`
	CountryCode    sql.NullString `json:"country_code"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.UserID,
		arg.FamilyName,
		arg.GivenName,
		arg.FamilyNameKana,
		arg.GivenNameKana,
		arg.Gender,
		arg.Birthdate,
		arg.CountryCode,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FamilyName,
		&i.GivenName,
		&i.FamilyNameKana,
		&i.GivenNameKana,
		&i.Gender,
		&i.Birthdate,
		&i.CountryCode,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, sub, email, email_verified_at, status, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const useAuthorizationCode = `-- name: UseAuthorizationCode :one
UPDATE authorization_codes
SET used_at = now()
WHERE code_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, code_hash, client_id, user_id, redirect_uri, scope, nonce, code_challenge, code_challenge_method, auth_time, expires_at, used_at, created_at
`

func (q *Queries) UseAuthorizationCode(ctx context.Context, codeHash string) (AuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, useAuthorizationCode, codeHash)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.AuthTime,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const withdrawUser = `-- name: WithdrawUser :exec
UPDATE users
SET status = 'withdrawn', updated_at = now()
WHERE id = $1
`

func (q *Queries) WithdrawUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, withdrawUser, id)
	return err
}
